-- CUSTOMER TABLE
CREATE TABLE CUSTOMER (
    CUS_ID INT PRIMARY KEY AUTO_INCREMENT,
    F_NAME VARCHAR(30) NOT NULL,
    L_NAME VARCHAR(30) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
);

-- EMPLOYEE TABLE
CREATE TABLE EMPLOYEE (
    EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    F_NAME VARCHAR(30) NOT NULL,
    L_NAME VARCHAR(30) NOT NULL,
    PHONE VARCHAR(15),
    EMAIL VARCHAR(75),
    EMP_ROLE VARCHAR(25) NOT NULL
);

-- SALESPERSON SUBTYPE
CREATE TABLE SALESPERSON (
    EMP_ID INT PRIMARY KEY,
    COMMISSION_RATE DECIMAL(5,2),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- TECHNICIAN SUBTYPE
CREATE TABLE TECHNICIAN (
    EMP_ID INT PRIMARY KEY,
    CERTIFICATION_LEVEL VARCHAR(50),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- MANAGER SUBTYPE
CREATE TABLE MANAGER (
    EMP_ID INT PRIMARY KEY,
    DEPARTMENT VARCHAR(50),
    OFFICE_LOCATION VARCHAR(100),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- VEHICLE TABLE
CREATE TABLE VEHICLE (
    VIN VARCHAR(17) PRIMARY KEY,
    MAKE VARCHAR(20) NOT NULL,
    MODEL VARCHAR(20) NOT NULL,
    YEAR INT NOT NULL,
    PRICE DECIMAL(8,2) CHECK (PRICE >= 0),
    COLOR VARCHAR(15)
);

-- SALE TABLE
CREATE TABLE SALE (
    SALE_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUS_ID INT NOT NULL,
    SALESPERSON_ID INT NOT NULL,
    SALE_DATE DATE NOT NULL,
    TOTAL_PRICE DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),
    FOREIGN KEY (SALESPERSON_ID) REFERENCES SALESPERSON(EMP_ID)
);

-- BRIDGE TABLE FOR SALE-VEHICLE
CREATE TABLE SALE_VEHICLE (
    SALE_ID INT,
    VIN VARCHAR(17),
    PRIMARY KEY (SALE_ID, VIN),
    FOREIGN KEY (SALE_ID) REFERENCES SALE(SALE_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (VIN) REFERENCES VEHICLE(VIN)
        ON DELETE CASCADE
);

-- FINANCE TABLE
CREATE TABLE FINANCE (
    FINANCE_ID INT PRIMARY KEY AUTO_INCREMENT,
    SALE_ID INT UNIQUE,
    PROVIDER VARCHAR(50),
    TERM_MONTHS INT,
    INTEREST_RATE DECIMAL(4,2),
    FOREIGN KEY (SALE_ID) REFERENCES SALE(SALE_ID)
        ON DELETE CASCADE
);

-- INSURANCE TABLE
CREATE TABLE INSURANCE (
    INSURANCE_ID INT PRIMARY KEY AUTO_INCREMENT,
    SALE_ID INT UNIQUE,
    COMPANY VARCHAR(50),
    POLICY_NUMBER VARCHAR(50),
    COVERAGE TEXT,
    FOREIGN KEY (SALE_ID) REFERENCES SALE(SALE_ID)
        ON DELETE CASCADE
);

-- SERVICE RECORD TABLE
CREATE TABLE SERVICERECORD (
    RECORD_ID INT PRIMARY KEY AUTO_INCREMENT,
    VIN VARCHAR(17),
    SERVICE_DATE DATE NOT NULL,
    DESCRIPTION TEXT,
    COST DECIMAL(8,2),
    FOREIGN KEY (VIN) REFERENCES VEHICLE(VIN)
        ON DELETE CASCADE
);

-- INVENTORY TABLE
CREATE TABLE INVENTORY (
    VEHICLE_ID VARCHAR(17) PRIMARY KEY,
    QUANTITY INT NOT NULL CHECK (QUANTITY >= 0),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VIN)
);
