CREATE TABLE CUSTOMER (
    CUS_ID INT PRIMARY KEY,
    F_NAME VARCHAR(30) NOT NULL,
    L_NAME VARCHAR(30) NOT NULL,
    PHONE VARCHAR(15), 
    EMAIL VARCHAR(75)
);

CREATE TABLE EMPLOYEE (
  EMP_ID INT PRIMARY KEY,
  F_NAME VARCHAR(30) NOT NULL,
  L_NAME VARCHAR(30) NOT NULL,
  PHONE VARCHAR(15),
  EMAIL VARCHAR(75),
  EMP_ROLE VARCHAR(25) NOT NULL
  );

CREATE TABLE SALESPERSON (
  EMP_ID INT PRIMARY KEY,
  COMMISSION_RATE DECIMAL(5,2),
  FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE TECHNICIAN (
  EMP_ID INT PRIMARY KEY,
  CERTIFICATION_LEVEL VARCHAR(50),
  FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE MANAGER (
  EMP_ID INT PRIMARY KEY,
  DEPARTMENT VARCHAR(50),
  OFFICE_LOCATION VARCHAR(100),
  FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE INSURANCE (
    INS_ID INT PRIMARY KEY,
    SALE_ID INT NOT NULL,
    PROVIDER VARCHAR(30) NOT NULL, 
    COVERAGE_DETAILS TEXT, 
    FOREIGN KEY (SALE_ID) REFERENCES SALE(SALE_ID)
);

CREATE TABLE FINANCE (
  FIN_ID INT PRIMARY KEY,
  SALE_ID INT NOT NULL UNIQUE,
  LENDER_NAME VARCHAR(50),
  LOAN_AMOUNT DECIMAL(10,2),
  INTEREST_RATE DECIMAL(4,2),
  TERM_LENGTH_MONTHS INT,
  FOREIGN KEY (SALE_ID) REFERENCES SALE(SALE_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE VEHICLE (
    VIN VARCHAR(17) PRIMARY KEY,
    MAKE VARCHAR(20) NOT NULL,
    MODEL VARCHAR(20) NOT NULL,
    YEAR INT NOT NULL,
    COLOR VARCHAR(15),
    MILEAGE INT,
    PRICE DECIMAL(8,2) CHECK (PRICE >= 0)
);

CREATE TABLE SALE (
  SALE_ID INT PRIMARY KEY AUTO_INCREMENT,
  VEHICLE_ID VARCHAR(17) NOT NULL,
  CUS_ID INT NOT NULL,
  SALESPERSON_ID INT NOT NULL,
  SALE_DATE DATE NOT NULL,
  FOREIGN KEY (SALESPERSON_ID) REFERENCES SALESPERSON(EMP_ID),
  FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),
  FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VIN)
);

