-- Step 1: Query without index
EXPLAIN
SELECT 
    S.SALE_ID,
    C.F_NAME,
    V.MAKE,
    E.F_NAME AS Salesperson,
    I.COMPANY AS InsuranceProvider,
    F.PROVIDER AS FinanceProvider
FROM SALE S
JOIN CUSTOMER C ON S.CUS_ID = C.CUS_ID
JOIN SALE_VEHICLE SV ON S.SALE_ID = SV.SALE_ID
JOIN VEHICLE V ON SV.VIN = V.VIN
JOIN EMPLOYEE E ON S.SALESPERSON_ID = E.EMP_ID
LEFT JOIN INSURANCE I ON S.SALE_ID = I.SALE_ID
LEFT JOIN FINANCE F ON S.SALE_ID = F.SALE_ID
WHERE S.TOTAL_PRICE > 25000;

-- Step 2: Add index
CREATE INDEX idx_total_price ON SALE(TOTAL_PRICE);

-- Step 3: Re-run query after indexing
EXPLAIN
SELECT 
    S.SALE_ID,
    C.F_NAME,
    V.MAKE,
    E.F_NAME AS Salesperson,
    I.COMPANY AS InsuranceProvider,
    F.PROVIDER AS FinanceProvider
FROM SALE S
JOIN CUSTOMER C ON S.CUS_ID = C.CUS_ID
JOIN SALE_VEHICLE SV ON S.SALE_ID = SV.SALE_ID
JOIN VEHICLE V ON SV.VIN = V.VIN
JOIN EMPLOYEE E ON S.SALESPERSON_ID = E.EMP_ID
LEFT JOIN INSURANCE I ON S.SALE_ID = I.SALE_ID
LEFT JOIN FINANCE F ON S.SALE_ID = F.SALE_ID
WHERE S.TOTAL_PRICE > 25000;

