-- Page 7: Show all products sold within a date range
SELECT 
    V.VIN, V.MAKE, V.MODEL, V.YEAR, V.PRICE, S.SALE_DATE
FROM SALE S
JOIN SALE_VEHICLE SV ON S.SALE_ID = SV.SALE_ID
JOIN VEHICLE V ON SV.VIN = V.VIN
WHERE S.SALE_DATE BETWEEN '2025-01-01' AND '2025-02-01';

